name: own_quest_app
description: "A new Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  injectable: ^2.3.2
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  go_router: ^8.2.0
  equatable: ^2.0.5
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  drift_dev: ^2.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700